### ISSUE TITLE
Mentions Scrollbar Missing

### ISSUE THREAD

**Issue by Snuupy** [realies/lounge-theme-amoled#4]
![image](https://user-images.githubusercontent.com/964538/82847109-4069c280-9eba-11ea-9921-48733625762d.png)

With https://github.com/realies/thelounge-theme-amoled/pull/3, I have not yet had the time to fix the mentions area. The scrollbar disappears, forcing the user to guess where the scrollbar is. See screenshot for details.

**Comment by realies** [comment]
Fixed in https://github.com/realies/thelounge-theme-amoled/pull/5, thanks for the help!
